name: Python CI

on: [push, pull_request]

jobs:
  type-check:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install "./python[dev]"
      - name: Type checks with mypy
        run: mypy python/src python/test

  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install "./python[dev]"
      - name: Test with pytest
        run: pytest python
